soft-fail: false
compact: true
create-baseline: false
quiet: true
evaluate-variables: true
directory:
  - .github/workflows
  - docker
framework:
  - all
skip-check:
  - CKV_DOCKER_2 # Ensure that HEALTHCHECK instructions have been added to container images
