repos:
# - repo: https://github.com/pre-commit/pre-commit-hooks
#   rev: v4.3.0  # Use the ref you want to point at
#   hooks:
#     - id: check-added-large-files
#     - id: trailing-whitespace
#     - id: check-merge-conflict
#     - id: check-symlinks
#     - id: end-of-file-fixer

- repo: https://github.com/bridgecrewio/checkov.git
  rev: "2.1.154"
  hooks:
    - id: checkov
      verbose: true
      # args: [--show-config=true]
      # args: [--show-config]
      # args: [--config-file=.checkov.yaml, --show-config=true]
      # args: [--external-checks-dir, 'checks']
      # args: [-d,  "./docker",]
      args: ["--config-file", ".checkov.yaml"]


# - repo: https://github.com/antonbabenko/pre-commit-terraform
#   rev: v1.74.1
#   hooks:
#     - id: terraform_checkov
#       args:
#         - --args=-d ./docker
        # - --args=--config-file __GIT_WORKING_DIR__/.checkov.yaml

# - repo: https://github.com/zricethezav/gitleaks
#   rev: v8.11.0
#   hooks:
#     - id: gitleaks
#       args:
#         - hook-config=--config __GIT_WORKING_DIR__/.gitleaks.toml
