repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args:
          - --branch=main

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier

  - repo: https://github.com/hadolint/hadolint
    rev: "v2.12.1-beta"
    hooks:
      - id: hadolint
        name: Lint Dockerfiles
        description: Runs hadolint to lint Dockerfiles
        language: system
        types: ["dockerfile"]
        entry: hadolint
        args: [--config=.hadolint.yaml]

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: "2.3.28"
    hooks:
      - id: checkov
        files: ""
        args: [--config-file=.checkov.yaml]

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.15.3
    hooks:
      - id: gitleaks
        args:
          - hook-config=--config .gitleaks.toml

  - repo: https://github.com/gitguardian/ggshield
    rev: v1.14.3
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
